### ISSUE TITLE
Documentation mentions unsupported unit initialization via list coercion

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1028]
In the [documentation for `Unit`](https://docs.zeek.org/projects/spicy/en/latest/programming/language/types.html#unit) we write about the initialization of unit constants:

> Spicy doesn’t support unit constants, but you can initialize unit instances through coercion from a list expression: `my_unit = [$FIELD_1 = X_1, $FIELD_N = X_N, ...]` where `FIELD_I` is the label of a corresponding field in `my_unit`’s type.

While we support and use that syntax to initialize `struct`s in generated HILTI code, I do not think we support that syntax in Spicy code, e.g., we reject following Spicy sample

```.r
module foo;

type X = unit {
    a: uint8;
    b: uint8;
};

function f() {
    local x: X = [$a = 1, $b = 2];
}
```

```.console
$ spicyc -j c.spicy
[error] c.spicy:9:19: syntax error, unexpected $-identifier
[error] spicyc: parse error
```

We should either remove the incorrect docs, or add support for it.

**Comment by rsmmr** [comment]
Interesting, I could have sworn this used to work at some point (we don't have a test, but that would be because with the old AST code, HILTI's structs would have covered it.)

Anyways, I would like it to work, so would prefer to leave the ticket open until fixed; and insert a link to the ticket into the docs until we do so.

**Comment by bbannier** [comment]
I filed #1036 for adding support for this and updated #1029 so it just adds a TODO referencing that new issue.
