### ISSUE TITLE
optional<bytes> differs between struct and tuple only as a parameter

### ISSUE THREAD

**Issue by ynadji** [zeek/spicy#1143]
This came up when trying to convert a struct to a tuple in Spicy to pass to Zeek. This same construct worked with `uint64` but failed with a cryptic error when I tried the same thing with `bytes`. It's possible other types would meet the same fate. Code and error follow:

```ruby
module Foo;

type Bar = struct {
  wutang: bytes &optional;
};

type BarTuple = tuple<
  wutang: optional<bytes>
>;

public function make_bar_tuple(bar: Bar): BarTuple {
  local nope: optional<bytes>;
  return (
    bar?.wutang ? optional(bar.wutang) : nope
  );
}
```

```
¡ spicy-build -o foo foo.spicy
[error] foo.spicy:14:5: types of alternatives do not match in ternary expression (optional<bytes> vs. optional<bytes>)
[error] spicyc: aborting after errors
```

However, if `bar` is instead declared locally, it compiles without issue:

```ruby
module Foo;

type Bar = struct {
  wutang: bytes &optional;
};

type BarTuple = tuple<
  wutang: optional<bytes>
>;

public function make_bar_tuple(): BarTuple {
  local bar: Bar;
  local nope: optional<bytes>;
  return tuple(bar?.wutang ? optional(bar.wutang) : nope);
}
```

(Fixed code to actually return tuple instead instead of `optional` - Robin).

**Comment by bbannier** [comment]
The issue here is that while type comparison initially invokes `sameExceptForConstness` two different type nodes without typeID or cxxID were created so we forward to the node equality check `Type::isEqual` which ultimately calls `operator==(const Type&, const Type&)` (which takes constness into account). The proper fix is probably to also add support for `sameExceptForConstness` on the node level.

**Comment by bbannier** [comment]
It looks like no quick fix is possible here. Instead of pushing `sameExceptForConstness` the proper fix is probably to instead move constness out of the type information, and then handle it explicitly where needed.

Unassigning myself for now.

**Comment by rsmmr** [comment]
The error message isn't great obviously, but semantically I think it's correct to reject this: `bar` comes in through a read-only parameter, meaning the `bytes` in `wutang` must not be modified. What we return however is a "normal" `optional<bytes>` wo/ constness, which would get around the read-only restriction at the caller if it were accepted. The `local` is read-write, that's why that works.

The other way to get this to work in making `bar` an `inout` parameter.

We should improve the error message, but not quite sure how to do that: we could use include constness information when rendering types, but that that might introduce confusion/noise elsewhere where constness often isn't relevant.

**Comment by rsmmr** [comment]
(deleted my previous comment as it wasn't right.)
