### ISSUE TITLE
Constructing hilti::rt::Library throws ghc::filesystem::filesystem_error for non-existing files

### ISSUE THREAD

**Issue by awelzel** [zeek/spicy#1232]
Playing around with writing a custom host application: Constructing a `hilti::rt::Library` instance with a non-existing path throws a `ghc::filesystem::filesystem_error`. While that may be by design, I had expected the subsequent `.open()` call  to fail and return a `Result` containing an error about the non-existing file.

Currently, one needs to do error handling using exceptions and handling the explicit result from `.open()` rather than one form or the other.

**Comment by bbannier** [comment]
This is "by design" to the extent that Spicy does not use one single mechanism to signal failures. While IMO using `Result`s consistently would make needed error handling clearer, the only way to return an error from a C++ constructor is an exception (and we do not plan to migrate all constructors to factory functions). We try to document throwing functions in the public API like we do e.g., [for the constructor of `Library`](https://github.com/zeek/spicy/blob/9445f040f915cf87d5f969dec6ceb14bf22fb617/hilti/runtime/include/library.h#L64-L69).

**Comment by awelzel** [comment]
> only way to return an error from a C++ constructor is an exception

Given there is `.open()` that has an error/success result, it just seemed surprising the constructor already fails that way. I had copied pieces from the tutorial and never checked the docs. Seems all is right then ;-)

**Comment by bbannier** [comment]
The hidden implementation bit here is that the constructor already performs [some work](https://github.com/zeek/spicy/blob/9445f040f915cf87d5f969dec6ceb14bf22fb617/hilti/runtime/src/library.cc#L53), mainly convert from relative to absolute paths so we do no depend on the working directory at the time of the `Library`'s construction anymore.
