### ISSUE TITLE
for loop over vector<bytes> and sink.write(): unsupported operator

### ISSUE THREAD

**Issue by awelzel** [zeek/spicy#1322]
When accumulating `bytes` into a `vector<bytes>` for later writing into a sink, it's not possible to use the nice/short `for` loop version.
```
module Test;

public type X = unit {
  on %init {
    self.s1.connect(new Y());
    self.buffered = vector(b"a", b"b", b"c");
  }

  on %done {
    for ( b in self.buffered )
      self.s1.write(b);
 }

 var buffered: vector<bytes>;
 sink s1;
};

type Y = unit {
  : bytes &eod;
};
```

```
root@def7564325e9:/src# spicy-driver sink-write-vector.spicy 
[error] sink-write-vector.spicy:11:7: unsupported operator: <sink>.write(<const bytes>)
[error] spicy-driver: aborting after errors
```

**Comment by awelzel** [comment]
Hmm, and `while` and `at(i)` gives the same.
```
  on %done {
    local i = 0;
    while ( i < |self.buffered| ) {
      self.s1.write(self.buffered.at(i));
      ++i;
    }
 }
```

Hmm... `self.s1.write(b"".join(self.buffered))`  works for now :man_shrugging:

**Comment by bbannier** [comment]
I believe the issue here on the type level  is that `sink::write` takes its bytes argument as `inout`, but the loop variable is const, so the signature does not match. It would seem that it should take the bytes as an `in` parameter instead.

Another workaround for const issues like this one one can sometimes introduce a mutable temporary (this introduces extra overhead at runtime).

```ruby
for ( b in self.buffered ) {
  local x = b;
  self.s1.write(b);
}
```
