### ISSUE TITLE
Add syntax to assert that a type matches 

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#140]
> would like to state what I am out-of-expediency assuming that the content matches and is unvarying
> 
> Whenever I express a filler attribute, I have a sinking feeling that I am neglecting the goal of Spicy scripts to correctly express a dissection defensively. When dissection assumes that all following length or relative pointer elements don't care about that content, which the script is presuming static or irrelevant, I would be willing as author to state what I am assuming that content matches. Then if content not matching that is encountered, it would raise exception so that the lazy decision does not propagate to later attributes which are lengths or pointer, where misalignment has disproportionate bad effects.
> 
> I am not overlooking that with the existing syntax I can validate. I am raising that there is a subtle difference between "specification says 8-bit pointers are used in the handled message types" and the reality is that "specification says 16-bit instead of 8-bit pointers are used when the message type is 11, but I have not coded for the possibility of the message type being 11, because that is not used in my problem space". Something like expressing an explicitly &unhandled-variant or something with similar brevity.

**Comment by duffy-corelight** [comment]
I have been hesitant to answer the question there posed, because though it would be a great boon, I wasn't sure how general the defensive constructs needed to be. &assert() is good. I have input https://github.com/zeek/spicy/issues/285 today as well, which might provide the general solution.

**Comment by duffy-corelight** [comment]
There won't be a satisfactory balance between explicitly using assert for defensiveness programming, and crafting .spicy scripts that are ready to use in production, until there is some kind of catch or resynchronize mechanism, even the acsac16 proposed:
```
type Requests = unit {
requests: list<Request> &synchronize;
};
```
might be enough. The issue is that .spicy scripting language will handle both "the plumbing for handling a series", which should be rock-solid, and made impossible to violate any invariants. But also the .spicy script will handle "detailed parsing of protocols", which might be, quoting acsac16 section 2.9 "... challenging if a format is complex or ill-documented". It is practical and probably of expedient necessity, to leave some cases as: "in violation of the invariants created by coding-assumptions", because of gaps in the code coverage relative to handling all of what a protocol stream could contain as potentialities. The "can't handle this packet, or this construct", however, should not abend the plumbing for handling a series. It should catch there, flag that situation, and move to the next packet/item in the ongoing stream.

**Comment by rsmmr** [comment]
We have `&requires` now. Once error recover is in place (#23), that will handle the part "move to the next packet/item in the ongoing stream".
