### ISSUE TITLE
Use of unset unit fields not rejected in unit `&size` attribute

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy#1466]
The following unit:

```
module Test;

public type test = unit {
	tag: uint8;
	length: uint16;
	data: bytes &size=self.length;
} &size=self.length+3;
```

Terminates with the following error:

```
$ printf '\x00\x00\x03abc' | spicy-driver test.spicy
[error] terminating with uncaught exception of type hilti::rt::UnsetOptional: unset optional value (test.spicy:3:20-6:2)
```

Using a size-check with size being sourced from a field inside a unit is a really useful feature, especially for TLV protocols, where the value can contain other types that can try to exceed the boundaries of the outer type. I encountered this during the reimplementation of the TLS analyzer; the old binpac analyzer uses this kind of construct a lot. The new parser currently doesn’t do as much checking - and I stumbled across this while trying to add it.

**Comment by bbannier** [comment]
While one side effect of `&size` is to validate that the given size is consumed, the issue here is that the unit's `&size` attribute is needed _before the unit gets parsed_ (when `self.length` is indeed unset) for setting up a view of limited size into the input stream, so this cannot work right now and should be rejected by a new validation.

The way to make this exact pattern work currently would be to use a `&requires` attribute and compute the size; unfortunately this requires random access for the unit.

```ruby
&requires=self.position() - self.input() == self.length + 3;
```

It might however be better to instead use `&size` attributes on individual fields (this also works with fields of unit type). This would e.g., also remove the manual computation of the size you have in your example.

```ruby
type X = unit {
    : bytes &eod;
};

type Y = unit {
    length: uint8;
    x: X &size=self.length;  # Fails if `X` consumes not exactly `self.length` bytes.
};
```

**Comment by rsmmr** [comment]
Looks like we should disallow use of `self` inside that outer `&size` expression.
