### ISSUE TITLE
Add "+=" operator for strings

### ISSUE THREAD

**Issue by Mohan-Dhawan** [zeek/spicy#1500]
Strings do not have the `+=` operator and concatenation is expensive when doing `a = a + b;`. An alternative is to convert strings to bytes and then concatenate, but it would be nice to have `+=` supported for strings natively.

**Comment by vpax** [comment]
Just to tease apart two separate issues here: (1) the streamlined simplicity of being able to express `a += b` to append strings (which I'm a fan of, it's quite analogous to existing operators in the language), vs. (2) the desire that concatenation of a new string to the end of an existing string be efficient (which I'm also of fan of!). To do that requires more than a `+=` operator - there would need to be a change to the internal representation of strings. I could see doing that, since we keep getting bitten by this sort of _O(N^2)_ behavior leading to DOS threats, but it's more involved than just supporting a `+=` operator.

**Comment by bbannier** [comment]
@vpax, could you clarify (2), in particular where you see quadratic performance for `+=`? Right now Spicy `string`' runtime type is a pretty thin wrapper around C++'s `std::string` so it inherits its tradeoffs and runtime characteristics (e.g., in the impl used by my compiler no naive capacity doubling on `s = s + s`, but still double iteration since strings fully own data). Simple benchmarks also seem to show that execution time has only a weak dependency on dependency on the length up to a couple thousand characters (likely: values fit in fast cache).

For extremely long strings it might still make sense to switch to a different data structure (e.g., non-continuous storage, more involved data structures like ropes or similar, ...), but the exact tradeoffs depend likely on what operations you would like to see made faster. One could e.g., make `s = s + s` fast by using a refcounted implementation for individual rope segments, but this could also lead to much slower string operations for e.g., short strings. Would you mind capturing the exact uses cases you have in mind in a fresh ticket or discussion so we can track this further?

**Comment by vpax** [comment]
@bbannier sorry I missed that this was in a Spicy context. I was referring to regular Zeek.
