### ISSUE TITLE
Cannot pass integers as `inout` parameters

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1583]
Even though we resolved #674 for `string` values, this still seems broken for other basic types like integers,

```ruby
module foo;

function inc(inout i: uint8) {++i;}
global x = 0;
inc(x);
```

```console
$ spicyc -dj hello.spicy 
[error] hello.spicy:14:1: call does not match any function: inc(<uint<64>>)
[error] hello.spicy:14:1:   candidate functions:
[error] hello.spicy:14:1:   - inc(<uint<8>>)
[error] spicyc: aborting after errors
```

**Comment by rsmmr** [comment]
This specific example seems fine: `x` is typed to `uint64` and we can't pass that to an `uint8`. However, there is a problem if the types are reversed: trying to pass an `uint8` to an `uint64` is accepted through coercion, but then the code doesn't work: it compiles but doesn't modify `i`. But the problem here is validation: with `inout` we need an exact type match, and must now allow coercion (because coercion always a temporary and there's not way to safely write the temporary back into the caller's argument). I'm going to add that validation, and a note to the manual.
