### ISSUE TITLE
Codebase tests aren't executed

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#1665]
Because `btest.cfg` is missing `codebase`:

```
TestDirs=hilti spicy ctest
```

Not fixing it right now because there are actually test failures that need to be addressed before activating this.

**Comment by bbannier** [comment]
The linting in `codebase/bashisms.sh` and `codebase/check-license-header` are done in pre-commit hooks since a long time and I'd argue we should just drop them now. In fact the test `codebase/bashisms.sh` fails for me since it picks up even files not part of the repo; `codebase/check-license-header` OTOH is more aggressively implemented with https://github.com/zeek/spicy/blob/36334a9932c78c3f37d5e44f0da2a176e6b17250/tests/Scripts/license-header.py. We should just delete them.

`codebase/visitors.sh` passes for me, but I am unsure what it does.
