### ISSUE TITLE
Convenience functions for string type

### ISSUE THREAD

**Issue by awelzel** [zeek/spicy#1807]
The `bytes` type has a few helpers like which `string` is missing.

* `starts_with()`
* `find()`
* `split()`
* `lower()` and `upper()`

I had a use for `starts_with()` and retreated to encoding the string to get access to `starts_with()`.

(The parser in question maybe should've used `bytes` instead of `string` throughout, but seems having these helpers may still be reasonable).

**Comment by evantypanski** [comment]
I think the linked PR adds enough, namely these helpers were added:

- `starts_with`
- `split`
- `split1`
- `lower`
- `upper`

And not `find` because that's at least less trivial than porting over helpers that `bytes` already has (due to the `Iterator`). Maybe a new issue or this can be reopened if that's necessary
