### ISSUE TITLE
Consider making `$$` available outside of units

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1812]
When parsing one can use `$$` in units to refer to the currently parsed value.[^1] This does not work when making a naked type declaration, i.e., a declaration just specifying a field, e.g.,

```ruby
public type uint24 = bytes &size=3 &convert=$$.to_uint(spicy::ByteOrder::Big);
```

```console
$ spicyc -dj foo.spicy
[error] foo.spicy:5:45-5:46: $$ is not available in this context
[error] spicyc: aborting after errors
```

The reason this fails is that `$$` is just syntactic sugar for an internal unit field `__dd` so `$$` turns into `self.__dd`; since there is no outer unit in this context this fails.

We could consider making `$$` available in such contexts as well. We could either do that by integrating `$$` deeper into the language, or by deferring resolving of `$$` for such constructs.

[^1]: Exact semantics depend on the context, e.g., `$$` in a hook is just the parsed value while in `foreach` hooks it is the current vector element.

**Comment by rsmmr** [comment]
There's more here that doesn't work: the `&size` isn't applied to parsing either. I think the higher-level issue here is that this declares a type, not a unit field; but `&size` and `&convert` are field attributes. Maybe we could add logic to transfer type attributes  over to fields in which the type is being used, but not fully sure immediately. 


For the record, the way to write this currently would be this:

```
type uint24 = unit { a: bytes &size=3;} &convert=$$.a.to_uint(spicy::ByteOrder::Big);```
```


Cc: @sethhall

**Comment by rsmmr** [comment]
Mulling over this more, I think I'd prefer to stick to the current approach to doing this: defining sub-units with a unit-level `&convert`. Seems cleanest because that doesn't mix up type and field declarations, and it's not much more to type. But we should then reject any attributes on type declarations that aren't supported there.

Two additional ideas: 

1. If we *really* wanted a way to define a field shortcut, we could introduce new syntax, like:

```
public field uint24 = bytes &size=3 &convert=$$.to_uint(spicy::ByteOrder::Big);
```

That would at least not mix up types and fields, but I'd still argue it's not worth the trouble.

2. Because this is presumably mostly about performance, we could instead internally optimize this so that for small, almost-trivial units with a unit-level `&convert`, we lift up the fields into outer units behind the scenes. That would need some care to ensure we're getting the same semantics with/without lifting, but if could whitelist the cases where we can ensure that and limit lifting to those.

**Comment by sethhall** [comment]
I really don't like adding that extra "field uint24" syntax.  If adding $$ outside of unit fields is an architectural problem I think it makes sense to just suggest the small unit with the unit level &convert.

When I originally brought up the $$ usage on a bare type it wasn't about performance, coming from a naive user perspective it just seems like that would work because mentally I don't put much difference between a type and a unit field but I can see how those might be handled differently internally.

If you wanted to get really crazy, you could even make $$ access on global types into a syntactic sugar thing by converting it internally into a unit with a single field and a unit level convert.  Hokey, but it actually feels pretty natural for a user.  Not sure it's worth it.

**Comment by sethhall** [comment]
I'm going to close this ticket, I don't think it's going anywhere right now and I'm sure it'll come up again later if it's needed.
