### ISSUE TITLE
Implement consistent attribute validation

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#1901]
Our validation of which attributes are allowed where is currently a bit messy/spotty. I think it would be helpful to centralize this. Couple ideas:

- Right now attributes are identified as strings throughout the code, making it easy to typo them in validation code and elsewhere (like checking for `&byte_order` instead of `&byte-order`). It would be good to switch to enums instead: we'd translate the name of the attribute into an enum label right at parsing time and then carry that around. (Note that the Spicy lexer has a list of valid attributes already).

- I think we could define a central table specifying for each attribute in which contexts it's allowed to be used. Like: `&eod` is a "parse attribute", `&cxxname` is a "type attribute", etc.. Then the validation code could just ask at the corresponding locations: is this attribute I'm seeing here a type attribute as I would expect? It might take a bit of trial-and-error to find the right context categories (e.g., is it "parse attribute", or instead a combination "field attribute" & "unit attribute"? Also: Would we have separate categories for type-specific parse attributes, like `&ipv4` only applies to address fields, or would be continue to hardcode that distinction directly in the validator?) Also note that an attribute may apply to multiple context categories. But independent of the details, the idea would be centralize the knowledge about where an attribute it expected to been.

(Much of this applies to properties, too, btw).

**Comment by evantypanski** [comment]
So looking at part 2 of this (with a [WIP commit](https://github.com/zeek/spicy/commit/a405f36f425e0362917f0eedf9871d23642e79fb)), I think minimally we could use a node's tag as some sort of key (or in a `switch` or something) in order to look up which attributes are allowed on.

I talked with both Robin and Benjamin and it seems like that's safe. We may lose some information for derived types - if that ends up having a noticeable impact then switching to using the whole `_node_tags` seems reasonable. I'll wait on that until there's a pressing need, though, because I'm not sure if there is one.

Doing this mapping isn't really complete. Some attributes may only be valid in some contexts, and we can't validate that just with a node's tag. I don't think there's a very easy way to get that full context though, since it's dependent on what node you're asking about. There are two important points here:

1) Fields are complex, there are a bunch of attributes that they accept. Then most of those attributes are context dependent. Just validating fields have the "field attributes" seems a bit crude. Maybe there will be another table that uses the field's attributes for the node, so that way you can have one table to verify questions like "Is this `&ipv4` attribute on an `addr` type within a field?" - separate from the question "Is this `&ipv4` attribute valid on a field?"
2) The validator should still be validating attributes apply in correct contexts, but I think some of these questions can be made easier, so it's easier to tell what attributes apply when. One example could be asking an `AttributeSet` if it `containsOneOf` a list of attributes. That's just spitballing, but having more convenient methods to ask about attributes seems like it could make it simpler to tell how an attribute is used.

So using `nodeTag` seems like it can fully verify the question "WHERE is this attribute used?" - asking HOW it's used may have to remain ad-hoc. I don't really know how to centralize that information, other than making it easier to see within the validator.
