### ISSUE TITLE
Cannot subtract number from iterators

### ISSUE THREAD

**Issue by evantypanski** [zeek/spicy#1920]
In the ["Changing input"](https://docs.zeek.org/projects/spicy/en/latest/programming/parsing.html#changing-input) section in the docs, there is a reference that seems like it implies you can subtract some number from an iterator:

> For random access, you’d typically get the current position through input(), subtract from it the desired number of bytes you want to back, and then use set_input to establish that new position.

So I tried `self.set_input(self.input() - 1);` and got:

```
[error] /Users/etyp/src/spicy-redis/analyzer/resp.spicy:25:28-25:43: unsupported operator: <const iterator<stream>> - <uint<64>
```

which seems exactly like the docs were telling me to do, so I got a little upset.

I don't see any `iterator - uint` ish operators anywhere - was this ever supported, or intended to be supported? I'd hardly call it "typical" if it's not supported :) so either that should be added or the docs changed.

But, I don't have the history of this to know which one it should be. I'd just prefer if you could subtract the number of bytes, that seems nice.

**Comment by rsmmr** [comment]
Hmm ... I think the docs are odd/wrong here. We do  have a `+` operator for these iterators but indeed no `-`. Iirc, that's on purpose because going back is often not going to work; there's a good chance that the data will have been discarded already. It's not always wrong, and in fact we'd also catch it on access and throw an `InvalidIterator`, but not providing `-` in the first place makes it harder to get surprised later at runtime.

So with that in mind, I don't know what the docs are trying to say there. :-) We should probably replace that with some version of "use input() to remember a position, then set_input() to go back there".
