### ISSUE TITLE
When iterating over a list constructor, all elements must have same type

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#196]
```
module Issue_196_negative_for_idx;

for ( indx in [1, -2, 3] )
    print indx;
```
```
2461 /usr/local/etc/tmp/spicy$printf "whatever\n" | build/bin/spicy-driver ../Issue_196_negative_for_idx.spicy
uncaught exception hilti::rt::Overflow: integer overflow
```

**Comment by rsmmr** [comment]
Yeah, I'd like to stay with the inference as I think it's quite convenient, and also similar to Zeek. 

What we can do here is add a check specifically "for" loops that all elements are of the same type. (I don't want to do that generally because we can be more relaxed in some other cases where implicit coercion allows to mix types).
