### ISSUE TITLE
request that spicy support the operator += for string += string → string

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#353]
Since spicy has support of operator += for 
bytes += bytes → bytes
as well as for vector, stream, and numbers, it would be a common situation that spicy script authors would attempt to use the operator += for string += string → string.
Best would be to eliminate this unnecessary limitation, which currently instead requires the repetition of the first string after = before +, by adding the support for operator += for string.

**Comment by duffy-corelight** [comment]
Seeing this in the error output:
```
[error] Dissassemble_0F3A.spicy:1828:11: unsupported operator: <string> += <string>
[error] Dissassemble_0F3A.spicy:1831:11: unsupported operator: <string> += <const string>
```
reminds me that it needs to be added for both string and const string.

**Comment by rsmmr** [comment]
Strings are immutable, which is why the operator doesn't exist. 

I'm not sure yet if that's what we'll want eventually (I'd say yes, but then `bytes` *is* mutable, so this seems inconsistent; on the other hand, making bytes immutable feels rather inconvinient). But either way, these are the current semantics and I'd rather not change either at the moment, so closing.
