### ISSUE TITLE
Consider support for switch statements consisting only of default cases

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#402]
As of 9502e536ece8de28f8043cced40b6bdd4b318355 we do not support `switch` statements consisting only of default cases. I am not sure if there are good technical reasons for this, but it appears arbitrary and a nuisance when prototyping.

```
$ cat /tmp/foo.spicy
module Foo;

type Bar = enum { a, b };

type P = unit {
    var x: Bar;
    switch (self.x) {
        # Bar::a -> : void {}   # Uncommenting this makes lets this module validate.
        * -> : void {}
    };
};

local x: Bar;
switch (x) {
    # case Bar::a: {}   # Uncommenting this makes lets this module validate.
    default: {}
}
```

```
$ spicyc -j /tmp/foo.spicy
[error] /tmp/foo.spicy:14:1-17:2: switch statement has no cases
[error] /tmp/foo.spicy:7:5-10:7: switch statement has no cases
[error] spicyc: aborting after errors
```

**Comment by duffy-corelight** [comment]
I had encountered this too. The non-default cases makes a great place to stub / architectural-boundary for a subsystems of code that go into a separate file. During the Edit-Compile-Run cycle, commenting those out, to just skip the need to satisfy them, is a majorly useful technique, so that a compile can complete without need for the other file(s) to be fully syntax remedied.
