### ISSUE TITLE
encapsulate more bits of precision in the time and interval datatypes

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/spicy#404]
```
module Issue_404;
import spicy;
global momentaryNow = spicy::current_time();

public type soonAfterThatToday = unit {
    var microsecondAfterOne: time = time(1.000001);
    var tenthOfmillisecondAfterOne: time = time(1.0001);
    on %done {
      print ("%s, %s, %s" % (momentaryNow, self.tenthOfmillisecondAfterOne, self.microsecondAfterOne));
    }
};
```
outputs
```
printf "4\n" |../../../../../Corelight/projects/spicy/build/bin/spicy-driver /usr/local/etc/tmp/Issue_404_lost_precision.spicy
2020-06-24T16:20:40.575311872Z, 1970-01-01T00:00:01.000100000Z, 1970-01-01T00:00:01.000000999Z
```
There isn't enough in the 53 precision bits of a double, when we want 30 bits devoted to nanoseconds. There isn't enough in the 53 precision bits of a double to get to the date 2554-12-31. So even just building up a year from four text digits has to special case to avoid the exception in the constructor.

I recommend to have a double and a uint64_t, and encapsulate any access to those, thus always providing both a range that extends more that 2584 years (to about a billion years of time), and also have accurate nanoseconds, per the print-format. I surmise by the devotion to nanoseconds in the CI tests, that we want to provide that specificity.

**Comment by duffy-corelight** [comment]
The special case to avoid the exception in the constructor that I refer to is in https://github.com/zeek/spicy/pull/378
line 45 of hilti/include/rt/types/time.h, `throw RuntimeError(fmt("Seconds %d cannot be represented as Time", secs));` added in https://github.com/zeek/spicy/commit/609d0dc37049c114f5cd45e2d91328e1931f9443

**Comment by rsmmr** [comment]
Yeah, `time` internally uses nanosecond resolution, so the question is how to construct a value. Double was chosen for the constructor because it's more convenient. I wouldn't just want to accept uint64 inside the constructor with different semantics (i.e., nsecs instead of secs for double) as that would be confusing. We had the same issue with the C++ API, and maybe the answer should be similar as well: we could add a tag argument that specifies resolution explicitly. Could look something like:
``time(1234, hilti::Resolution::Nanoseconds)``, and we could default to match current bevahiour, i.e., `time(1)` and `time(1.0)` would both mean seconds. (Casting from an integer has the same issue btw, it's currently interpreting the value as secs).

**Comment by duffy-corelight** [comment]
I picture that the available constructors are two (or perhaps a third, which takes both). All constructors take an argument in seconds. The constructor which takes uint64_t argument will use that as seconds and set the internally represented nanoseconds portion to zero. The double argument will set the internal seconds from the leading portion, and the represented internal nanoseconds from the decimal portion. But thereafter all calculations, cascade any particular large accumulation of seconds (I think anything more than a week's worth, so that there are never more than 18 bits of the internalDouble devoted to the integer portion) out of the internalDouble, adding those instead onto the internalUint64Seconds.
