### ISSUE TITLE
Get Spicy to build on CentOS 7

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#451]

**Comment by rsmmr** [comment]
@bbannier take a look at #457. It's close, but some tests are failing, see if you can figure out what's going on there.

**Comment by bbannier** [comment]
Spicy (both Spicy itself and the runtime code it generates) currently requires fairly good support for C++17.

While one can install devtoolset packages on centos-7, the design goal of devtoolset is to provide a modern _build environment_ while the runtime environment still only uses packages from the base system.  Since centos-7 ships with a libstdc++ from the gcc-4.8 series which has poor C++17 support this makes it hard to support Spicy on this system, even with the newest devtoolset installed.

One approach to overcome this would be to attempt to link Spicy statically against just libstdc++ to remove the runtime dependency on the system library. This is the approach taken in [this branch](https://github.com/zeek/spicy/tree/topic/bbannier/issue_451); this branch also contains a [patch](https://github.com/zeek/spicy/commit/d0808c29439993dc01d154e42cdc7e568c612a7f) to emit code which can be compiled with the environment set up by the [`Dockerfile` for centos-7](https://github.com/zeek/spicy/blob/topic/bbannier/issue_451/docker/Dockerfile.centos-7). This approach fails since we still transitively link against libstdc++ through other direct dependencies.

In order for Spicy to be built and its artifacts to be deployed more work seems to be needed. A possible direction could be to provide a complete, modern libstdc++ on the system which can be dynamically linked to (not just the shim provided by devtoolset). This would involve compiling a full gcc stack, building Spicy in that environment and then deploying the libstdc++ together with Spicy-produced HLTO files (probably: by adjusting dynamic library loading via e.g., setting a custom `LD_LIBRARY_PATH`).

We are closing this ticket as `WONT_FIX` at this moment, but are willing to make non-intrusive changes to Spicy to accomodate building and deploying on centos-7.

**Comment by bbannier** [comment]
Once we get Spicy to build on centos7, we could switch the `zeek_packages` CI job over to get some coverage of the platform.
