### ISSUE TITLE
Switch the Bison files' struct value type to variants

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#46]
The current struct is pretty inefficient. We can't use a union, but Bison has a variant type: https://www.gnu.org/software/bison/manual/bison.html#C_002b_002b-Variants

Bison maintainer Akim Demaille has an example of efficient C++ use
in flex & bison here:
https://gitlab.lrde.epita.fr/vcsn/vcsn/tree/master/lib/vcsn/dot

**Comment by rsmmr** [comment]
From: #215 we should add more readable token description to the Spicy parser for better error message (iirc, the HILTI parser has them already).

**Comment by rsmmr** [comment]
Seems our current Bison parsers are quiet inefficient in their state management. With the branch in #984, I get the following breakdown of allocations for a tiny hello-world:

```
=== Top-20 type-erased instances (#max/#current)
hilti::Type       11419 (58.50%)          86 ( 6.75%)
hilti::ID        5702 (29.21%)          91 ( 7.14%)
hilti::expression::detail::Expression         490 ( 2.51%)          53 ( 4.16%)
hilti::Attribute         267 ( 1.37%)          28 ( 2.20%)
hilti::Declaration         222 ( 1.14%)          73 ( 5.73%)
hilti::ctor::detail::Ctor         164 ( 0.84%)          50 ( 3.92%)
hilti::type::Bool         105 ( 0.54%)           4 ( 0.31%)
hilti::AttributeSet         103 ( 0.53%)          19 ( 1.49%)
```

Looking at memory allocations with Instruments, it turns out that almost 90% of them are inside the parsing code. My guess is that we're creating & copying many `yystype_spicy` during parsing.
