### ISSUE TITLE
Track data offsets during parsing

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#494]
For some host applications (Wireshark) it can be useful to know the offsets into the data where fields were parsed from. We can store those inside the structs. Might need to be an optional feature that one would  enable on demand during parser generation.

`ParseError` can likewise provide the offset where parsing failed.

**Comment by rsmmr** [comment]
I'm thinking that we can add a `uint64_t __offsets[N][2]` to all structs generated from Spicy units. During parsing, we then record begin/end offsets for each field `i` into this array at `_offsets[i][0/1]`. And we extend the type information for struct fields with corresponding pointers into the `__offsets` array,

This should all be optional, we can add a compiler flag whether to generated this additional instrumentation.

**Comment by duffy-corelight** [comment]
The uint64_t _offsets[0][0] seems to me the obvious choice that tracks the current parsing position. And _offsets[0][1] is either always 0, or is greater than 0 during a &parse-from or &parse-at. This idea also solves another concern that I had when I read `each field i into this array ` because field i suggests to my ear that the first field identified is field 1.
