### ISSUE TITLE
Validating domain of enum fields seems not very streamlined

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#499]
When parsing units with enum-type fields it seems users should always write validation for a `&convert` function to produce a non-`Undef` value, i.e., that the encountered value is indeed in the domain of the enumerator.

Given a module
```
module Foo;

type P = unit {
  foo: uint16 convert=E($$);
  switch(self.foo) {
    E::A -> bar: uint16;
    # Seems impossible to put a case for `E::Undef` which triggers an error here.
  };
};

type E = enum { A = 0x01 };
```

The workaround seems to be to declare `foo` similar to this,
```
foo: uint16 convert=E($$) { if (self.foo==E::Undef) assert False; }
```

Looking at our example parsers we almost never perform such validation, but instead let a `ParseError` from the unhandled `Undef` case propagate up.

This seems weird as parsers almost everywhere else automatically enforce that parsed values are in the domain of the field being parsed. Naively one would expect a parse error to be triggered when parsing `foo` in above example, but this seems not possible since users cannot raise this exception.

I feel the most declarative approach would be to declare `foo: E` which could hook in automatic validation of the parsed data for `Undef`; alternatively we could allow users to raise parse errors themselves.

**Comment by rsmmr** [comment]
Parts of this is intentional, but there's also a bug. 

It's on purpose that unknown values turn into `Undef` and don't trigger an error automatically. Note that the actual value is not lost:

```
on P::foo { print self.foo; }
```

```
# printf '\000\001\000\000' | ./a.out
E::A, 1
# printf '\000\002\000\000' | ./a.out
E::<unknown-2>, 2
[error] spicy-driver: terminating with uncaught exception of type spicy::rt::ParseError: parse error: no matching case in switch statement (a.spicy:5:3-8:5)
```

The reason for accepting this is that with protocols it is a typical use case for enums to want to capture opcodes of some kind where we won't know all possible values in advance. This allows to put nice tags on those values we do know, but work with any  others as well.

That said, I would expect the following two options to work:

1. To enforce seeing a known value, adding `&requires=(self.foo != E::Undef)` to the field (and we could  add an implicit boolean conversion to enums to make that nicer, which would check for `Undef`).

2. Adding a `case` for `Undef` like this: `E::Undef -> void { print "unknown enum value"; }` (that wouldn't trigger an error this way of course; we do still need that way to trigger a parse error manually)

But here comes the bug: Neither of these options work right now. Looks like enums don't compare correctly against `Undef` right now. That we need to fix.

**Comment by rsmmr** [comment]
Actually I don't like my suggestion anymore:  `Undef` is a distict state and comparing against it should only yield true if both operands are indeed `Undef` (not: one is simply label-less). Same applies to a boolean conversion: should give true only if != `Undef`. So I suggest we do a method instead, just to need find a nice name (`is_known()`?)
