### ISSUE TITLE
Clarify error messaging when attempting JIT without support compiled in

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#507]
Latest 0.4.0-884.dirty (master 6b77b11) spicy-driver immediately prints `[error] spicy-driver: no parsers available` Whereas running spicy-build on the same .spicy file correctly compiles and runs giving the correct output, but then that is followed by a print of `[error] spicy-driver: no parsers available`

**Comment by duffy-corelight** [comment]
This is the first local rebuild of spicy that I've done since 27-Apr-2020. spicy-driver takes proportionately longer on long scripts, and fails if there are failing asserts or syntax errors. But every successfully compiled script just prints `[error] spicy-driver: no parsers available` 
build/bin/spicy-driver -l then given a successful .spicy file prints with different capitalization, and a trailing period, and no [error] prefix, just `No parsers available.`
An older 0.4.0-154 that I still have, behaves properly, as does spicy-build on the same input.

**Comment by rsmmr** [comment]
I can't reproduce this. Tried on both Mac and Linux:

```
# printf '\x00\x00\x27\x10\x2a' | spicy-driver tests/spicy/types/unit/basic.spicy
[$f1=(not set), $f2=(not set)]
10000
42
[$f1=10000, $f2=42]

# spicy-driver -l tests/spicy/types/unit/basic.spicy
Available parsers:

       Mini::Test
```

Any chance your build is just in a weird state? Have you tried a clean checkout?

**Comment by duffy-corelight** [comment]
Alas, always a chance my build is just in a weird state. I hit it with a variety of hammers as I continue to try to gain understanding. Thanks for giving this a repro attempt. I worked on it all evening, trying to be able to deliver the solution along with the first-report (that is the reporting style I prefer). But as the night grew long, I decided to admit I was struggling, and would benefit seeing if it was something everyone on that version was experiencing. You can set it aside (I'm not held up by this, since I can use spicy-build), and I'll try various A-B things as I get time to do so, until I resolve it. Whatever I'll report will then either include what the key change was, or that I did go all-the-way to a fresh installation and had it disappear.

**Comment by duffy-corelight** [comment]
Turns out to be a consequence of ./Configure without the --with-cxx-compiler=/Users/Duffy/Documents/work/Corelight/projects/maestro/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++

Maybe we can be a little more explicit in our message at execution in this situation, where spicy-driver is running with no-JIT run-time. It is misleading to users, that it does the .spicy compilation step (taking expected time and reporting syntax check failures if any), and then without any more output messaging, just fails to execute anything, not even global statements.

**Comment by rsmmr** [comment]
Ack, improving the error messaging makes sense.
