### ISSUE TITLE
more restrictive type-adherence; where previously supported implicit cast<>

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#532]
Two ways .spicy code written in April needed to be updated, to compile with now more restrictive type-adherence. In order to avoid an explicit cast<> operation in line of code
```
      self.lengthOfPrebytes = |self.usablePrebytes|;
```

I had to change
```
<     var lengthOfPrebytes: uint16;
---
>     var lengthOfPrebytes: uint64;
```

And to support a bool result from the bit7 in
```
type evex = unit {
  scnd : bitfield(8) {
     pP: 0..1;
     always1 : 2;
     negVvvv: 3..6;
     wFromXop: 7;
     };
```
I couldn't find anything more expedient than to add an explicit cast<bool> operation in line of code
```
<       RexPrefixW = self.scnd.wFromXop;
---
>       RexPrefixW = cast<bool>(self.scnd.wFromXop);
```

Is this more restrictive type-adherence unintended as an artifact of underlying code changes, forcing the script writers to be explicit, where previously the parser supported some implicit conversion without cast<> ?

**Comment by rsmmr** [comment]
Rejecting the size example seems right to me, it's a lossy conversion to go from 64 bits to 16 bites, and should indeed require a cast (or type change) to make it work.

The `wFromXop` example feels generally right as well, too: implicit to-bool conversions happen only in some specific contexts to avoid surprising some effects; we follow C++ there. It should, e.g., work inside an `if`: `if ( self.scnd.wFromXop ) ...`.
That said, I do see the appeal of implicitly considering a 1-bit value equivalent to a bool. I need to think about if that's something easy to support internally (initial guess is no, because we're passing that bit around as an `uint8` and may have lost the information that it's just a 1-bit at the point where we need it; and I wouldn't want to allow it for all `uint8`).

**Comment by duffy-ocraven** [comment]
I can see wisdom in the script author needing to be explicit when the intention is to discard part of the potential range.
I am not as-much in agreement with you on the second though. For instance refactoring an expression out of an if statement, in order to perhaps apply an && afterwards, doesn't seem like it is ever not just as readily implicitly-coerceable to bool. Even uint8 can unambiguously implicitly-coerced to bool. Everything either is 0 or it is True.

**Comment by rsmmr** [comment]
If you refactor it out, you can always do an explicit `... == 0` to make that value a boolean, which I would argue makes it more readable, too, by making explicit what your interpretation of the value is.

I'll go ahead and close, not planing on changing this at least for the time being.

**Comment by duffy-ocraven** [comment]
Closing this is fine. You make an excellent point that: "...an explicit ... == 0 to make that value a boolean, making explicit  interpretation of the value represents" before it is a boolean, is absolutely justified. "which value is intuitively False" is not universal. The C convention for process return result from main has the opposite, where a non-zero is failure.
