### ISSUE TITLE
converting from bytes &size=1 to uint8

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/spicy#533]
```
    var opcodeToUse: uint8;
    nonprebyte: bytes &size=1;
    on nonprebyte {
      self.opcodeToUse = cast<uint8>(self.nonprebyte);
```
has been reporting of a syntax error since at-least April:
```
 [error] line 201:26: unsupported operator: cast<<type<uint<8>>>>(<bytes>)
```
The following is an alternative syntax which does achieve the conversion:
```
      self.opcodeToUse = cast<uint8>(self.nonprebyte.to_uint(spicy::ByteOrder::Big));
```

Had it been our design intention to have such restrictive type-adherence, forcing the script writers to be so explicit in converting from `bytes &size=1` to `uint8`, where the parser could instead support implicit conversion?

P.S. The way that a syntax error for `unsupported operator: cast` uses literal `<`and `>` intermixed with that abundance of figurative ones, perhaps deserves to be revised to a different expression for that specific syntax error, not using figurative  `<`and `>` characters (or perhaps not using quite so many).

**Comment by rsmmr** [comment]
It's intentional that the cast doesn't work (it's not well-defined what would happen with arbitrary `bytes` instances). It works to go through iterators: `*begin(self.nonprebyte)` or `*self.nonprebyte.at(0)`. 

Open to other suggestions for making this nicer, we could e.g. add a method to directly retrieve the byte at a certain offset, like: `byte_at(i: uint<64>) → uint8`

**Comment by duffy-ocraven** [comment]
Going through iterators: `*begin(self.nonprebyte)` or `*self.nonprebyte.at(0)` is satisfactory. No need for additionally providing `byte_at`. It hadn't occurred to me to iterate a &size=1 member, but that works fine.
