### ISSUE TITLE
Add support for FreeBSD

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#575]
First step here is to understand if this is a pretty straightforward thing to do, or if there's some large issue hiding somewhere that would require more work. I'd think it's the former and then we can make this a 1.0 item and turn FBSD into an officially supported platform with CI integration.

Concretely, there are two main platform-specific things I can think of that will need attention:

1. There's a small number of `#ifdef LINUX/APPLE` in the code where we'll need to cover `FREEBSD` as well.
2. Check that our fiber implementation in particular works well and efficiently.

**Comment by bbannier** [comment]
I spun up a quick freebsd-12 build. Without looking too deep into it I was unable to build spicy-rt due to some build issues, e.g.,
```
ld: error: duplicate symbol: local_ccl_blank
>>> defined at jlocale.c:44 (../3rdparty/justrx/src/jlocale.c:44)
>>>            jlocale.c.o:(local_ccl_blank) in archive lib/libhilti-rt.a
>>> defined at jlocale.c:44 (../3rdparty/justrx/src/jlocale.c:44)
>>>            3rdparty/justrx/CMakeFiles/jrx-objects.dir/./src/jlocale.c.o:(.text+0x160)

ld: error: duplicate symbol: local_ccl_digit
>>> defined at jlocale.c:37 (../3rdparty/justrx/src/jlocale.c:37)
>>>            jlocale.c.o:(local_ccl_digit) in archive lib/libhilti-rt.a
>>> defined at jlocale.c:37 (../3rdparty/justrx/src/jlocale.c:37)
>>>            3rdparty/justrx/CMakeFiles/jrx-objects.dir/./src/jlocale.c.o:(.text+0x120)
...
```

After fixing adding `#include <sys/socket.h>` in places using `AF_INET*`, and patching the build to exclude `backtrace` functionality for now (currently that is `if ... LINUX` in cmake) I was able to successfully build and execute `hilti-rt-tests` (which tests basic fiber uses cases), and it passed.

This looks feasible.

**Comment by rsmmr** [comment]
Covered by #582, closing this one.
