### ISSUE TITLE
Add cleanup hook to units

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#690]
Right now we don't have a hook to reliably clean up external/global state when a unit gets destroyed. (`%done` only executes when parsing succeeds, but will not trigger in error cases; and `%error` isn't guaranteed to trigger for all kinds of error). Thinking to add something like `%cleanup` or `%finish` that will be guaranteed to execute eventually.

**Comment by bbannier** [comment]
Do you think we could fix `%error` so it is invoked for all errors so we don't have to introduce another hook? Looking at the documentation it isn't clear to me for which kinds of errors `%error` wouldn't trigger.

I think it would be much nicer if we could fix the implementation so`%done` and `%error` are invoked on all exits. Otherwise with a `%finish` hook we'd introduce something non-obvious which isn't needed most of the time; this could lead users to write implementations which fail in subtle scenarios. Scenarios with more complicated code could still invoke shared cleanup logic from both `%done` and `%error`.

**Comment by rsmmr** [comment]
> Do you think we could fix `%error` so it is invoked for all errors so we don't have to introduce another hook?

Maybe, need to see when exactly it triggers or not (i.e., which exceptions we catch there).

> I think it would be much nicer if we could fix the implementation so`%done` and `%error` are invoked on all exits. 

Yeah, I can see that argument. The counter argument is that then one will often have to duplicate the same clean up logic so that it's included in both `%done` and `%error` hook (say, if you need to remove state from a global map once the unit is done.).

**Comment by 0xxon** [comment]
So - just from a user perspective...

I would vote for both. So - having %error trigger on all errors, as well as having a %finish trigger so one only has to specify cleanup-type things once :)

**Comment by duffy-ocraven** [comment]
I would favor %finally over %finish. No difference in meaning, but %finish gives me a sense where sometimes "things that go to %error don't finish" would inaccurately lead an author astray. Plus the words finish and done have no universal intuitive ordering, whereas finally does semantically come after those.

**Comment by rsmmr** [comment]
Ok, so I'm thinking to go with the "both" approach:

- Confirm/ensure that `%error` runs for any kind of error that abort the current parsing process
- Add a `%finally` hook that is guaranteed to run on both normal and erroneous termination
