### ISSUE TITLE
Provide Spicy-land Port constructor

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#723]
Currently `Port` values can only be constructed from literals in Spicy. We should provide a constructor so users can construct them from an `uint16` and a `hilti::Protocol`.

This issue was first reported by user Tom Carroll on [Zeek Slack](https://zeekorg.slack.com/archives/C012CQV1K29/p1611768550080300).

**Comment by bbannier** [comment]
After discussion with @rsmmr the following seems like a reusable approach:

- introduce a HILTI AST node `expression::BuiltinFunction<ReturnType, ArgType...>(cxxname: string, args: vector<Expression>`
- on the HILTI side this is treating like a function
- in codegen it emits a call to `cxxname` with the give arguments

**Comment by rsmmr** [comment]
one additional note: because the new node will remain in the AST (and not be replaced by a function call) we'll need to perform type coercion for the arguments: that will need a visitor in `hilti/.../apply-coercions.cc` and can probably reuse the `coerceCallArguments()` method there if we express the builtin's parameters as `declaration::Paramater`. The visitor for `New` is doing something similar for the unit arguments.
