### ISSUE TITLE
Feature request: stream iterator to current position

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy#731]
It would be neat if there was a way to get a stream iterator to the current position. I know this is basically equivalent to just calling input() + offset(). However, often you want to add something to the current position, and then save that - and the syntax for that is slightly ugly at the moment:

```
self.input() + (cast<uint32>(self.offset()) + 4);
```

Additionally - it would be neat to have variants for "current position" (as in - current element is not parsed) and "following position" (so - just behind the element that currently is being parsed).

**Comment by duffy-ocraven** [comment]
Echoing my comment from #709. Decision to make self.offset return a value that needs a cast to use arithmetically with other variables is a decision that I recommend be reversed. Every piece of code that picks up a length or offset from the data, but requires a cast, lets the author more easily make the mistake of casting that to an int, because when they do that, the compile-time syntax report goes away which makes it seem like progress. But which is always a bug if the MSB is set in what the data had.

**Comment by rsmmr** [comment]
> It would be neat if there was a way to get a stream iterator to the current position.

yeah, makes sense. We still need to look at  #709 as well, but a method to get the current iterator seems useful either way.

> Additionally - it would be neat to have variants for "current position" (as in - current element is not parsed)

That's what a method returning the equivalent of `input() + offset()` would yield; that's my preference.

> and "following position" (so - just behind the element that currently is being parsed).

We could do that, too. The downside is that every position we want provide we need to remember first --- and that's happening inside a hidden field inside the `unit` instance being parsed. Adding more of those increases fields the overhead. Question is if that's worth it.

**Comment by 0xxon** [comment]
> We could do that, too. The downside is that every position we want provide we need to remember first --- and that's happening inside a hidden field inside the `unit` instance being parsed. Adding more of those increases fields the overhead. Question is if that's worth it.

That is fair - I can be completely happy with the former :)
