### ISSUE TITLE
AST keeps changing error

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy#737]
I get the following error:

```
[internal-error] hilti::Unit::compile() didn't terminate, AST keeps changing
```

On a unit, which admittedly is a bit broken, and rather large. I sadly could not figure out how to reduce is to a smaller example.

To reproduce, check out commit ``c159d8f9e95caf456617254e107fa4c64866ab21`` of this repo, cd to spicy/lib/file-formats and execute ``spicy-driver -d exif.spicy``

**Comment by bbannier** [comment]
Looking at the AST transformation progress the only changes being produced after the first couple iterations are changes in IDs. We pretty early on record an error that the name of the module and of a type defined in it [are identical](https://github.com/zeek/spicy/blob/a30a6f201500031431e5e4d994de3e78db4754e5/spicy/lib/file-formats/exif.spicy#L1-L3),
```
$ head ast-2.tmp
# EXIF: AST after iteration (round 2)
- Module %1 (exif.spicy:1:1-624:3)  [ERROR] type namespace EXIF::EXIF is ambiguous  [ERROR] type namespace EXIF::EXIF is ambiguous  [ERROR] type namespace EXIF::EXIF is ambiguous  [ERROR] type namespace EXIF::EXIF is ambiguous  [ERROR] type namespace EXIF::EXIF is ambiguous  [ERROR] type namespace EXIF::EXIF is ambiguous  [ERROR] type namespace EXIF::EXIF is ambiguous  [ERROR] type namespace EXIF::EXIF is ambiguous
    | EXIF -> declaration::Module %1292 <id="EXIF">
    | EXIF -> declaration::Type %504 (original %543) <linkage="public">
    | ExifTag -> declaration::Type %12 <linkage="private">
    | ExifType -> declaration::Type %2 <linkage="private">
    | IDFValue -> declaration::Type %508 (original %569) <linkage="private">
    | IFD -> declaration::Type %505 (original %550) <linkage="private">
    | IFDField -> declaration::Type %507 (original %566) <linkage="private">
    | __register_EXIF_EXIF -> declaration::Function %1402 <linkage="init">
```

This seems to lead to a situation where new IDs are generated. Making this converge might also fix the issue here.
