### ISSUE TITLE
Add language support to explicitly trigger a parse error

### ISSUE THREAD

**Issue by jsiwek** [zeek/spicy#768]
Wasn't sure if it's intended for `&requires` to be evaluated before field hooks:

```
module Test;

public type MyUnit = unit {
    s: bytes &size=4 &requires=(self.flag);

    on s { self.flag = True; }

    var flag: bool;
};
```
```
$ printf 'test' | spicy-dump test.spicy
[fatal error] terminating with uncaught exception of type spicy::rt::ParseError: parse error: &requires failed ($$ == test) (test.spicy:4:22)
```

Initially thought that field hooks might get evaluated first in real example here and found otherwise:

https://github.com/zeek/spicy/compare/topic/jsiwek/pe#diff-36ceb1dc5c1f8f65e1fb3553b2d552ef12f58b3651f1df59aafa9e6c3fafc63eR64-R67

* Generally seems to be lack of documentation on evaluation order and adding that could help.

* For what I was trying to do, would be convenient if the order was different, but realize it's kind of arbitrary/implicit, so might generally be better to have an explicit way to induce parsing errors from within arbitrary hook-code itself.  E.g. either with a `throw` or special `return` value.  Kind of like mentioned in previous error-handling discussions https://github.com/zeek/spicy/issues/89#issuecomment-648637582 and https://github.com/zeek/spicy/discussions/616#discussioncomment-185009

**Comment by rsmmr** [comment]
Order here is intentional, with the reasoning being that the hook can already rely on the requirement being enforced. Agree that we need a way to trigger an error. This has come up often enough now that we should just add a way to do that (but leave more general error handling/recover to >1.0). I think the ideas on the table so far are:

1. `throw "<msg>"` triggering a `ParseError` carrying msg (could also be some other keyword, like `fail`.

2. `throw <exception>`: HILTI has user-defined exceptions already but we don't really expose them in Spicy yet. Would need to think about semantics of different exception classes here.

3. `requires <conditition>` enforcing the condition similar to `&requires`.

I'm thinking to do (1) or (3) (or both) now, and leave (2) as a generalization to later

**Comment by duffy-ocraven** [comment]
Regarding (1) or (2) or (3) (or both 1 and 3), I encourage doing whatever triggers the same machinery as: for example, an attempt to parse outside of the data does now. We want whatever the author has chosen to write for handling run-time errors, whether those be due to their coding mistakes, or author misconceptions, or the incoming data being non-conformant to expectations, to also be what any author-defined run-time errors will do. There should not be any author-thought required, for treating library exceptions as any different from author-written exceptions.

**Comment by rsmmr** [comment]
(Renaming ticket)
