### ISSUE TITLE
Using || to determine size in evt file creates double.

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy#798]
Creating an evt file with a content like

```
on a -> event a(|self.member|);
```

leads to spicy wanting to send a double to Zeek. This seems rather unintuivite - and should probably just be converted into a count.

One can manually cast it to an uint64 and then it works, but that looks rather weird:

```
on a -> event a(cast<uint64>(|self.member|));
```

**Comment by 0xxon** [comment]
Well, right repository now :)

**Comment by 0xxon** [comment]
In addition - the fact that a conversion error in the evt leads to %error being raised seems a tad weird (and sent me on an 1.5 hour-long chase in the wrong direction).

**Comment by bbannier** [comment]
The issue here seems to be that the implementation of this `Size` operator return whatever the runtime library container defines as`size()` return value; for most containers we directly expose the underlying C++ stdlib functions for `size` so that e.g., `rt::Vector::size` returns a `std::vector::size_t` (likely: `std::size_t` which could be e.g., a naked `unsigned long long`).

Now when computing conversions to Zeek values, we do have a [specialization for our safe integers](https://github.com/zeek/spicy/blob/9604a8b20aa408e12a16cfef22f004525b01f713/zeek/plugin/include/runtime-support.h#L257-L258), but due the C++ conversion semantics the [specialization for `double`](https://github.com/zeek/spicy/blob/2e16514f98e8dabaf0403a4048eb3bd18b334013/zeek/plugin/include/runtime-support.h#L267) is picked instead.

We should probably do two things: add value conversion specializations for integer types, and change the runtime containers to return safe integers for `size()`.
