### ISSUE TITLE
Regex parsing stops prematurely with input from filter

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#860]
```
module Test;

public type X = unit {
    x: b"x";
    : /[ \n]*/;
    # : /[ \n]*/;   # Works if we enable this.
    y: b"y";

    on %init { self.connect_filter(new F); }
    on %done { print self; }
};

type F = unit {
    %filter;
    x: /[^\n]*\n/ { self.forward($$); }
    y: /[^\n]*\n/ { self.forward($$); }
};
```

```
# printf "x\n y\n" | spicy-driver y.spicy
[error] terminating with uncaught exception of type spicy::rt::ParseError: parse error: expecting 'y' (y.spicy:8:8)
```

It looks like the regex in line 5 stops matching after the data from the 1st `forward()` has been received, even though the data from the 2nd forward would extend the match further. Repeating the same regex right aftwards makes this work.

**Comment by bbannier** [comment]
Observation: this seems work in incremental mode for chunk sizes in `[1..4]`.

**Comment by bbannier** [comment]
I see a seemingly related bug in `RegExp`s ending in `*`:

```.cpp
auto re = RegExp("x*", regexp::Flags{.use_std = true});
auto m = re.tokenMatcher();
CHECK_EQ(m.advance("xa"_b), std::make_tuple(-1, 2)); // FAILS: only gets `[1, 1]`.
```
We should be able to extract two bytes here, and be able to consume more input; instead the matcher only extracts `x` and claims to not make any more progress with more input.

This seems related since for input `x\n y\n` the parsing in the initial report leads to the first `\n ` to be split by the `Filter` two; the dummy matcher `/[ \n]*/` seems to then claim to be down already after seeing the the first `\n` without consuming the following space. The commented out line then can consume that as well. This seems to be supported by what I see when simplifying the reproducer further: Replacing the dummy matcher `/[ \n]*/` with `/\n*/` and the space in the input with `\n` produces the same faulty result.

**Comment by bbannier** [comment]
This seems to be a bug in justrx.

**Comment by bbannier** [comment]
My code sample above doesn't apply here and JRX seems to be fine. I posted a patch to fix our side of code interfacing with it which seems to have been the issue.
