### ISSUE TITLE
Problem accessing map elements

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#861]
```
module Foo;

type Object = unit {
    x: int8;
};

global o: Object;
o.x = 42;
global m = map<string, Object>("foo": o);

print m["foo"].x;
```

```
# spicyc -j x.spicy
/private/var/folders/g4/hc_gy8h56v567ds8qtwzqkww0000gp/T/hilti-rt-test-slh8if/Foo.cc:202:50: error: indirection requires pointer operand
      ('hilti::rt::map::detail::AssignProxy<std::__1::basic_string<char>, hilti::rt::ValueReference<__hlt::Foo::Object> >' invalid)
    hilti::rt::print(hilti::rt::optional::value((*Foo::__globals()->m[std::string("foo")]).x, "x.spicy:13:7"), hilti::rt::Bool(true));
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bbannier** [comment]
An even more reduced example:

```.r
module Foo;

type Object = struct {
    int8 x;
};

global o: Object;
global m = map<string, Object>("x": o);

m["x"].x;
```

The issue here is that on the runtime level `Map`'s `operator[]` returns an `AssignProxy` and not a value. On the AST level  we resolve `m["x"].x` to a member access which directly codegens an `m["x"].x`.

I believe to make this work in a generic way `memberAccess` shouldn't emit the naked value, but instead forcibly cast it to the resolved type (so we e.g., here get an `Object` and not the `AssignProxy` over the `map` during member access). Unfortunately, this will lead to much nosier code emitted during codegen.

As a separate issue, `Map` should have all of the following to make assignments work:
```.cpp
operator const V&() const& { return _map.get(_key); }
operator V&() & { return _map.get(_key); }
operator V() && { return _map.get(_key); }
```
