### ISSUE TITLE
CI: Add OpenSUSE Leap 15.2

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#882]
Zeek recently added opensuse-15.2 to their list of supported platforms, see e.g., zeek/zeek#1482. We should add it to our CI as well.

**Comment by 0xxon** [comment]
It actually turns out to not be this bad. This needs #885 merged, for bison-3.0 compatibility. Afterwards, you just need to install gcc9 and gcc9-c++, in addition to the typical packages you need for Zeek (see Zeek ci dockerfile).

I then was able to get it compiled with all tests passing issuing:
```
CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9 ./configure --prefix=$HOME/spicy/install --enable-debug --disable-broker-tests --generator=Ninja --disable-zkg --disable-zeekctl --disable-python --disable-archiver 
./configure --prefix=$HOME/spicy/install --with-c-compiler=/usr/bin/gcc-9 --with-cxx-compiler=/usr/bin/g++-9 --with-zeek=$HOME/spicy/install --enable-debug --generator=Ninja --build-zeek-plugin=yes
```

When you create tests for this, note that the Zeek packets for OpenSUSE Leap 15.2 are currently created with the default gcc (so 7.5.0).  I did not test if there are any compatibility problems with using a different compiler to compile Zeek vs spicy.
