### ISSUE TITLE
Add exception handling to Spicy

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#89]
Spicy doesn't have any of the exception pieces yet:

[ ] type `exception`
[ ] statement `throw`
[ ] statement `try ... catch`

This is all available on the HILTI side already, just need to expose & document it. Will need a bit of thought on how the types for built-in HILTI & Spicy exceptions get exposed so that become accessible from Spicy code.

**Comment by rsmmr** [comment]
We should also add a way to explicitly trigger a parse error from inside hooks so that normal error handling can kick in, similar to what `&requires` does). This could be a `throw` with a `ParseError` exception, or we could add some syntactic sugar for that (like a `requires` statement?). This is also related to the idea in #285 of explicitly labeling invariants.

**Comment by duffy-corelight** [comment]
There is already documented a %requires statement in 5.1.1. Basics in section entitled "Enforcing Parsing Constraints". The 5.1.1 passage is nine screenfuls long, without any numbered subsections. It could benefit from subsections in the Table-of-Contents.

**Comment by rsmmr** [comment]
Separate discussion of error handling #616.

**Comment by rsmmr** [comment]
Actually I'm going to close this in favor of that discussion.
