### ISSUE TITLE
Errors with recent clang-tidy

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#915]
I'm getting a number of errors with clang-tidy 12 when running across the code base. It's pretty noisy, though could be just a a couple issues being repeated; haven't investigated yet.

**Comment by bbannier** [comment]
To add some more detail, the most prominent issue I am seeing from clang-13 is diagnostics due to usage of `IntrusivePtr` in `ast::Node`. Since this seems to be triggered from a number of places I am not sure yet what the workaround is, or if there might even be still potential for misuse in the flagged code.
