### ISSUE TITLE
Add validation that unit var initializers are constants

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#939]
Unit var initializers are set when a units begins parsing, not where they are declared in a unit. This means that it e.g., is not possible to use other parsed results (not sure if we need to restrict to just constants, though).

```.r
module Foo;

public type X = unit {
    x: uint8;
    var y: uint8 = self.x;
};
```

```
$ echo 123 | spicy-driver bla.spicy
[error] terminating with uncaught exception of type hilti::rt::UnsetOptional: unset optional value (bla.spicy:5:20)
```

We should add validation that unit var initializers do not use unset values.

**Comment by rsmmr** [comment]
Strictly speaking it's not really an error, I consider this to be working as expected currently. But I agree that reporting it still makes sense because it pretty useless to access a value that will always be unset. However, that applies only to fields of the current unit; using other non-constant values is fine & supported.

**Comment by rsmmr** [comment]
Could use some clarification in the docs too I suppose about `var` initialization.
