### ISSUE TITLE
spicy-plugin tests fail on freebsd12

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#954]
Since this morning most `spicy-plugin` tests part in the freebsd12 CI job fail. I noticed this after merging #951, but was able to exclude this being triggered by the changes from that PR by rerunning the freebsd12 job for the previous commit which had succeeded earlier, https://cirrus-ci.com/task/5653959097450496. This seems to indicate that something about image seems to have changed (e.g., change to the Zeek package).

Typically when the FreeBSD project bumps packages we see the changes at some later point (~weeks) once the images Cirrus uses are updated, so we might need to go back in history to see what happened to the image.

I cannot currently reproduce this with freebsd12 Vagrant images (works in both `3.2.14` and `3.2.24`).

When we ran into similar package issues in the past we typically made the job not required and tracked whether the issue fixed itself.

**Comment by dhoelzer** [comment]
I'm having the same issue on a clean install under Linux.  spicy-plugin tests fail during zkg install.  Lots of things like this:

```
[#1] zeek.event-cond ... failed
  % 'btest-diff output' failed unexpectedly (exit code 1)
  % cat .diag
  == File ===============================
  == Diff ===============================
  --- /tmp/test-diff.1118889.output.baseline.tmp	2021-07-16 12:32:58.457652079 +0000
  +++ /tmp/test-diff.1118889.output.tmp	2021-07-16 12:32:58.445652048 +0000
  @@ -1,5 +0,0 @@
  -1, OpenSSH_3.8.1p1
  -1, OpenSSH_3.9p1
  -3, OpenSSH_3.9p1
  -4, OpenSSH_3.8.1p1
  -5, OpenSSH_3.8.1p1
  =======================================
```

I'm just starting to investigate but thought it might be related to this thread.

**Comment by rsmmr** [comment]
Are you installing from git main? Note that that is unstable at the moment, per the Slack message below. The release versions should be fine.



PSA: I’m about to merge a larger restructuring of the three Spicy repositories (Spicy itself, Zeek plugin, Zeek analyzers).  The two main changes are:
 (1) Spicy itself will no longer come with the Zeek plugin/analyzers as submodules, and it won’t be able to build them in-tree anymore. Building them in-tree was already off by default, and was useful primarily for development. It became a time-sink to maintain and is now gone. A result, the build setup for all three repos became substantially more simple.
(2) The Zeek plugin is internally restructured to support Zeek’s new --include-plugins configure option so that it can now be compiled statically into the Zeek binary.
The 3 repos might be a bit unstable for a little while until this is fully merged and CI turns green everywhere. I’ll send a note here when it’s done.

**Comment by dhoelzer** [comment]
Ah, yes.. 😊 I am. 😊

 
I’m not on the Slack but I’ll join.

 
Thanks.. 😊. And hi!  Nice to see you again. 😊


 
From: Robin Sommer ***@***.***>
Reply-To: zeek/spicy ***@***.***>
Date: Friday, July 16, 2021 at 1:07 PM
To: zeek/spicy ***@***.***>
Cc: David Hoelzer ***@***.***>, Comment ***@***.***>
Subject: Re: [zeek/spicy] spicy-plugin tests fail on freebsd12 (#954)

 
Are you installing from git main? Note that that is unstable at the moment, per the Slack message below. The release versions should be fine.

PSA: I’m about to merge a larger restructuring of the three Spicy repositories (Spicy itself, Zeek plugin, Zeek analyzers). The two main changes are:
(1) Spicy itself will no longer come with the Zeek plugin/analyzers as submodules, and it won’t be able to build them in-tree anymore. Building them in-tree was already off by default, and was useful primarily for development. It became a time-sink to maintain and is now gone. A result, the build setup for all three repos became substantially more simple.
(2) The Zeek plugin is internally restructured to support Zeek’s new --include-plugins configure option so that it can now be compiled statically into the Zeek binary.
The 3 repos might be a bit unstable for a little while until this is fully merged and CI turns green everywhere. I’ll send a note here when it’s done.

**Comment by rsmmr** [comment]
This should be fixed with the recent reorg updates, CI is now all green for FreeBSD.
