### ISSUE TITLE
`configure` quirks

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy#960]
When configuring the 1.1 release tarball, I'm seeing a couple of odd outputs:

```
-- Found Git: /usr/local/bin/git (found version "2.32.0")
-- git Version: v0.0.0
-- Version: 0.0.0
```

and

```
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by bbannier** [comment]
This is odd. We check the release tarball in CI in a ubuntu-20 container. I triggered that job again and it did pass. I also checked the 1.1.0 release tarball on macos which also succeeded.

Could you share more about what link you used to download the tarball, what system you were using, and the used `./configure` invocation?

**Comment by rsmmr** [comment]
Did you check your output if you see those lines? `configure` is still succeeding for me (and the build then works as well), it's just producing that spurious output as part of its reporting.

**Comment by bbannier** [comment]
> -- git Version: v0.0.0
> -- Version: 0.0.0

This is from the CMake setup of `3rdparty/benchmark`. Since that directory is not a Git repo anymore when working from a release tarball you are seeing a "default version" `0.0.0`.

> fatal: not a git repository (or any of the parent directories): .git

This is from our CMake setup when we try to detect whether the current Spicy version corresponds to a Git tag. This detection cannot work when run from release tarballs, but like you said it has minimal effects for users (a package would have a full version number in its name instead of being `spicy-dev`; since we want that simplified version in order to link to CI artifacts this behavior seems acceptable). I'll add a patch to swallow that error message from Git.

We also seem to have an issue with our CI task validating release tarballs, namely that it doesn't actually build and test the tarball, but the checkout instead. I'll post a patch for that as well.
